# Generated by Django 4.2.7 on 2023-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
