# Generated by Django 4.2.7 on 2023-12-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blog_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='frontImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='media',
            field=models.URLField(),
        ),
    ]
