# Generated by Django 4.2.7 on 2023-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blog_frontimage_alter_imagefile_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contentImage',
            field=models.ManyToManyField(blank=True, null=True, to='api.imagefile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='story',
            field=models.ManyToManyField(blank=True, null=True, to='api.contentsection'),
        ),
    ]
