# Generated by Django 4.2.7 on 2023-12-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blog_contentimage_alter_blog_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='frontImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
