# Generated by Django 4.2.7 on 2023-12-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_blog_frontimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='media',
            field=models.ImageField(upload_to=''),
        ),
    ]
